-- migrate:up
CREATE TABLE teamA (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	birth INT NOT NULL,
	contact VARCHAR(100) NOT NULL,
	gender VARCHAR(100) NOT NULL,
	mbti VARCHAR(10) NULL
);

-- migrate:down
DROP TABLE teamA;
