-- migrate:up
CREATE TABLE authors (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  frist_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NULL,
  age INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE authors;


