-- migrate:up
CREATE TABLEposts (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_no INT NOT NULL,
  title VARCHAR(300) NOT NULL,
  post VARCHAR(2000) ,
  likes INT NOT DEFAULT '0',
  post_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  post_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP UPDATE CURRENT_TIMESTAMP
) 

-- migrate:down
DROP TABLE users;