-- migrate:up
CREATE TABLE posts (
  no INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  post_id VARCHAR(200) NOT NULL,
  post_title VARCHAR(300) NOT NULL,
  post VARCHAR(2000) NOT NULL,
  post_created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  post_updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

-- migrate:down

DROP TABLE posts;